### ISSUE TITLE
Ler os dados do quadro resumo do usuário

### ISSUE THREAD

**Issue by wagnermc506** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#14]

**Comment by manuengsf** [comment]
Descrição 

- Capturar dados do quadro resumo do usuário , o usuário deve estar logado para esta funcionalidade funcione. 

Tarefas 

- verificar se o usuário esta logado 
- verificar se o usuário esta logado no quadro resumo 
- Extrair dados do quadro resumo 
- testar com selenium se os dados do quadro resumo do usúario correspondem  aos dados capturados por esta funcionalidade da extensão . 

critérios de aceite

- a captura dos dados passou no teste de aceitação com selenium.

**Comment by wagnermc506** [comment]
Devido a falta de tempo, não foram realizados os testes com o selenium.
