### ISSUE TITLE
Implementar no Pop-up um menu inicial

### ISSUE THREAD

**Issue by wagnermc506** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#15]
Neste menu, deverão aparecer botões das funcionalidades da extensão

**Comment by manuengsf** [comment]
Descrição 

- Implementar um menu inicial para que o usuário possa dar os primeiros comandos na extensão . 

Tarefas 

- fazer linkar com as funções já implementadas no backend.
- fazer a tela do menu inicial.

critérios de aceite 

- testar manualmente para verificar se aos comandos  se refletem em instruções correspondentes na extensão .

**Comment by fmaachadoo** [comment]
## Issue inviável no momento para a release 2:

Não há motivos para implementar essa funcionalidade agora. Essa implementação no momento só criaria poluição visual para o usuário e em retorno não teria uma grande gama de funcionalidades linkadas ao menu
