### ISSUE TITLE
Destacar na página de ofertas as matérias do curso do usuário

### ISSUE THREAD

**Issue by wagnermc506** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#16]

**Comment by manuengsf** [comment]
Descrição 
 
- Destacar na pagina de oferta as materias do curso do usuario para que o usuario saiba que materias pertecem ao seu curso e possa melhorar sua analise sem se perder no mar de disciplinas oferecidas pelo matricula web. 

Tarefas

- Extrair materias do fluxo do curso do usuário 
- marcar na lista de oferta de materias 
- testar com selenium para verificar se todas as materias que estão no fluxo do curso do usuario aparecem marcadas. 

Criterios de aceite

- Passar no teste com Selenium
