### ISSUE TITLE
Identificar os pré-requisitos das matérias

### ISSUE THREAD

**Issue by wagnermc506** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#17]

**Comment by manuengsf** [comment]
Descrição

- Realizar a identificação dos pré-requisitos  , gerar a identificação dos pre requisitos  a partir da extração dos dados do matricula web.

Tarefas

- extrair os dados do matrícula web.
- identificar os pre requisitos 

critérios de aceite

- realizar teste no selenium onde os pré-requisitos coletados diretamente pelo matricula web , devem ser iguais aos pré-requisitos coletados pela extensão.

**Comment by thiagolsg** [comment]
Pré-requisitos salvos na API Chrome.storage. 

Os arquivos foram separados entre requisitosNode.js e requisitos.js. O requisitosNode é onde está a parte implementada para o projeto, enquanto o requisitos.js é o que lido pela extenção(é o mesmo código com as dependências do node sendo usadas nele).

Para informações da estrutura do salvamento, acesse este [documento](https://github.com/fga-eps-mds/2019.2-Recomendacao-de-Matricula/blob/developer/docs/chromeStorage.md).
