### ISSUE TITLE
Identificar os horários das matérias

### ISSUE THREAD

**Issue by wagnermc506** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#18]

**Comment by manuengsf** [comment]
Descrição 

- Realizar a identificação do horario das materias , gerar a identificação do horario das materias a partir da extração dos dados do matricula web . 

Tarefas 

- extrair os dados do matrícula web.
- identificar o horário das matérias.  
- realizar teste no selenium onde os horários coletados diretamente pelo  matricula web , devem ser iguais aos horários coletados pela extensão .

critérios de aceite

- Extensão passou no teste de identificação de matérias com selenium

**Comment by thiagolsg** [comment]
Por alteração do escopo final do projeto, viu-se que não era mais necessário coletar os horários de cada disciplina
