### ISSUE TITLE
Editar o Readme.md de acordo com os padrões do Github

### ISSUE THREAD

**Issue by wagnermc506** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#19]

**Comment by manuengsf** [comment]
Descrição 

  Elaborar o Readme para que ele fique bem explicado passando a ideia do projeto para os visitantes que desejem conhecer melhore contribuir para o projeto  o projeto e não somente para os desenvolvedores como está hoje. 

Tarefas

- estudar como fazer um bom readme baseado nos outros projetos da disciplina . 
- fazer uma breve descrição do projeto
- fazer um guia de uso para o projeto  
- fazer um guia de como contribuir para o projeto

criterios de aceite
  
  

- A descrição deve mostrar as principais funcionalidades funcionalidades do projeto e para que o projeto existe .
-   O guia de uso deve mostrar como instalar o projeto e como usar o projeto.
- O guia de como contribuir deve  convidar as pessoas para contribuir alem de apontar para o codigo de conduta.

**Comment by fmaachadoo** [comment]
Importante implementar tópicos sobre a Guia de Contribuição e o Link para a Wiki

**Comment by fmaachadoo** [comment]
Readme finalizado para a versão atual e pronto para a Release 2
