### ISSUE TITLE
Implementar no Popup uma tela de boas vindas

### ISSUE THREAD

**Issue by wagnermc506** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#20]
Essa tela deverá aparecer na primeira vez que o usuário logar no site com a extensão ativa.

**Comment by manuengsf** [comment]
descrição 
  
   A Popup de boas vindas deve aparecer sempre que o usuario pela  logar primeira vez , na extensão desde que ele esteja logado no site do matricula web. como se fosse para sauda-lo .

Tarefas 
   
  -verificar quando o usuario logou pela primeira vez na extensão 
  -gerar Popup de Boas vindas.

**Comment by fmaachadoo** [comment]
## Issue não será implementada no momento

Na reunião da equipe foi decidido que essa issue seria contra os conceitos de Experiência do Usuário e tornaria o uso da extensão menos prático.
