### ISSUE TITLE
Verificar se o usuário está logado no site Matrícula Web

### ISSUE THREAD

**Issue by wagnermc506** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#21]

**Comment by manuengsf** [comment]
Descrição 

- A extensão para funcionar precisa ter o usuario logado na pagina do matricula web da internet , para que possa desta forma capturar os dados do historico do aluno e das materias oferecidas no semestre e possa a partir disso gerar uma recomendação de matricula adequada ao estudante. 

 
Tarefas

- Testar  para ver se a rede esta funcionando  
-   identificar se o usuario esta logado na pagina do matricula web da internet. 
-   realizar teste com selenium verificando se o usuario esta ou não logado  no site do matricula web
 
critérios de aceite
  
- A extensão passou no teste de login com o selenium

**Comment by fmaachadoo** [comment]
# Conclusão:

Essa função já foi implementada em conjunto à um feedback pro usuário na popup da extensão.
Na página de passo a passo para que a extensão funcione corretamente há um feedback para o usuário sobre o login.
