### ISSUE TITLE
Criar um web-crawler para recolher os pré-requisitos de cada matéria 

### ISSUE THREAD

**Issue by thiagolsg** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#25]
Utilizando funções do browserify para recolher as informações do pré-requisitos na página da matéria no matricula web

**Comment by manuengsf** [comment]
O Crawler para ser bem realizado pode ser quebrado nas seguintes funções 
   -  Navegar entre paginas das materias 
   -  coletar dados referentes as materias   
   - testar a captura de dados com selenium . 

Criterios de Aceitei 

- Crawler passou no teste com Selenium .
