### ISSUE TITLE
Salvar os pré-requisitos no chrome.storage.local

### ISSUE THREAD

**Issue by thiagolsg** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#26]
Estruturar os dados salvos no chrome.storage.local de forma que seja possível associar os códigos das disciplinas com os seus respectivos pré-requesitos

**Comment by manuengsf** [comment]
Descrição 
  
  Salvar os pre-requisitos no armazenamento do sistema , visando consulta-las depois. Este armazenamento tem como principal vantagem sua simplicidade no uso , sendo por isso escolhido , pois bancos de dados e arquivos são muitos mais complexos de se utilizar . 

Tarefas 
  
- configurar paste in build para receber  salvar dados no chorme-storage-local
- configurar arquivo para salvar dados no chorome-storage-local 
- salvar dados no chorome-storage-local  
  
criterios de aceitei 
 
Teste de unitario para  chegar se os dados colocados para serem salvos estao realmente sendo salvos no chorome-storage-local.
