### ISSUE TITLE
Implementar aprimoração no Destaque: Matérias com Equivalência

### ISSUE THREAD

**Issue by fmaachadoo** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#32]
# Verificar e destacar matérias com equivalência

<p> Na UNB há matérias diferentes mas que são equivalentes, ou seja, elas têm o conteúdo ministrado similar, se não idêntico, e as matérias com equivalência são pré-requisitos das mesmas matérias, sendo que se uma dessas matérias forem concluídas já é o suficiente para suprir o requisito das matérias pre-requisitadas.

## Condição de aceitação para fechamento desta issue:

<p> Quando matérias que são equivalentes são destacadas juntas, ou se caso da matéria não precisar ser destacada então ambas as matérias equivalentes não serem destacadas na página da oferta de matrículas

**Comment by thiagolsg** [comment]
Esta issue é totalmente inviavel uma vez que uma matéria equivalente pode não possuir os mesmos pré-requisitos, esta funcionalidade também não é muito útil uma vez que na pagina do currículo já e compara as matérias equivalentes
