### ISSUE TITLE
Desenvolver um Crawler para a página do Matrícula Web com o objetivo de capturar as informações desejadas 

### ISSUE THREAD

**Issue by fmaachadoo** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#4]

**Comment by matheussbernardo** [comment]
Se ajudar de alguma forma, provavelmente nao ajude. Mas eu fiz um [crawler](https://github.com/matheussbernardo/MWCrawler) em Elixir

**Comment by manuengsf** [comment]
O Crawler para ser bem realizado pode ser quebrado nas seguintes funções 

 -  Navegar entre paginas de interesse
 -  coletar dados das paginas  
 - Armazenar no google Chorome Storage
 - testar a captura de dados com selenium . 

Criterios de Aceitei 

   - Realizar teste no selenium comparar os resultados por meio do selenium com os resultados por meio do crawler Ele deve coletar os mesmos dados dados do crawler.

**Comment by wagnermc506** [comment]
Todos os Crawlers(quadro resumo, requisitos e histórico) implementados.
