### ISSUE TITLE
Implementar função que verifica se o usuário acessou a página do histórico 

### ISSUE THREAD

**Issue by wagnermc506** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#44]
## Implementação de verificação
Verificar se o usuário acessou o histórico, para que possa existir um feedback para o próprio usuário sobre se a captura de dados ocorreu.

## Condição de aceitação para fechamento dessa issue:
Quando estiver disponível a passagem deste dado para o front-end

**Comment by fmaachadoo** [comment]
Finalizado com sucesso!
