### ISSUE TITLE
Desenvolver um front-end com funcionalidades integradas em botões ou outros inputs do usuário

### ISSUE THREAD

**Issue by fmaachadoo** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#5]
Front-end ultilizando React e MaterialUI

---

## Pontos importantes ##

- Os Components do React têm que estar modularizados, ou seja, organizados em arquivos diferentes de forma que facilite a leitura do programa e a manutenção.

- Usar 'states' para verificar e mudar o estados das diferentes 'páginas' da pop-up

**Comment by manuengsf** [comment]
Descrição 

- Descrever um Frontend  que seja integrado em botões ou outros inputs do usuário , que o usuario possa interagir com facilidade . 

Tarefas 

- Montar Frontend com botões e inputs do usuário.
-Integrar Frontend com funções no Backend.
- testar manualmente para ver se a os botões correspondem a funções no backend . e se não existem  funções de backend não cobertas por botões ou comandos que possam ser dados pelo usuario.  

 
Critérios de aceite

  - botões correspondem a funções no backend 
  - comandos correspondem a funções no backend
 - não existem funções no backend não coberta por botões ou comandos .

**Comment by fmaachadoo** [comment]
Finalizado com sucesso!
