### ISSUE TITLE
Desenvolver a Wiki do projeto

### ISSUE THREAD

**Issue by fmaachadoo** [fga-eps-mds/2019.2-Recomendacao-de-Matricula#6]

**Comment by manuengsf** [comment]
Descrição 

- Desenvolver a Wiki do projeto a partir  dos outros documentos do projeto . para com isso criar uma referencia entre os diferentes documentos do projeto e dar ao projeto uma organização. 

Tarefas 

- escrever a wiki. 
- linkar os outros  documentos a wiki 

Critérios de aceite

- Linkar todos os documentos , montar um texto coeso  que vai naturalmente passando de um documento para outro .

**Comment by fmaachadoo** [comment]
Foram adicionados os artefatos sobre a documentação do projeto na Wiki, nativa do próprio repositório, contendo os seguintes itens:

+ Documento de Arquitetura
+ Documento de Visão
+ Histórias de Usuário
+ Plano de Comunicação
